# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

KEYTIMEOUT=40
ZVM_KEYTIMEOUT=0.4
ZVM_ESCAPE_KEYTIMEOUT=0.15
ZVM_LAZY_KEYBINDINGS=false

plugins=(
  git
  zsh-vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

zvm_bindkey vicmd '_' vi-first-non-blank

# Option-backspace to delete last word
zvm_bindkey viins $'\e\x7f' backward-kill-word

zvm_bindkey viins $'\e[1;3D'      backward-word      # iTerm Alt-Left  (CSI 1;3D)
zvm_bindkey viins $'\e[1;3C'      forward-word       # iTerm Alt-Right
zvm_bindkey viins $'\e[1;5D'      backward-word      # Linux Alt-Left  (CSI 1;5D)
zvm_bindkey viins $'\e[1;5C'      forward-word       # Linux Alt-Right

# User configuration

# -- Use fd instead of fzf --

export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
    export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
    ssh)          fzf --preview 'dig {}'                   "$@" ;;
    *)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
  esac
}

fzfpid() {
  ps -ef | sed 1d | fzf | awk '{ print $2 }'
}


for map in emacs vicmd viins; do
  bindkey -M $map -r '^G'
done

export EDITOR=nvim
export LS_COLORS="di=1;34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

alias k=kubectl
alias py=python3
alias ls=eza
alias fzfb="fzf --preview=\"bat --color=always {}\""

eval "$(starship init zsh)"

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)" && alias cd=z || true
fi

autoload -Uz add-zle-hook-widget

_load_fzf() {
  source <(fzf --zsh)
  [ -f ~/.fzf-git-sh/fzf-git.sh ] && source ~/.fzf-git-sh/fzf-git.sh
}

add-zle-hook-widget zle-line-init _load_fzf

if [ -n "$SSH_AUTH_SOCK" ]; then
  AUTH_SOCK="$HOME/.ssh/auth.sock"
  ln -sf "$SSH_AUTH_SOCK" "$AUTH_SOCK"

  export SSH_AUTH_SOCK="$AUTH_SOCK"

  if [ -n "$TMUX" ]; then
    tmux set-environment -g SSH_AUTH_SOCK "$SSH_AUTH_SOCK"
  fi
fi
